#!/usr/bin/env python3
"""Turn scripts/clinical_pearls.tsv into main/boards/qdtech/tab5/tab5_clinical_pearls.inc.

Checks that every character exists in the compiled 28 px font (tab5_dynamic_symbols.txt
plus printable ASCII) and that each pearl fits the 2-line home card.
Usage: python3 scripts/generate_clinical_pearls.py [--check]
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TSV = ROOT / "scripts/clinical_pearls.tsv"
OUT = ROOT / "main/boards/qdtech/tab5/tab5_clinical_pearls.inc"
CATS = {"icu": "kPearlsIcu", "ger": "kPearlsGer", "crrt": "kPearlsCrrt"}
MAX_TITLE_CHARS = 9        # + 3 for the "重症：" style prefix, 430 px title label
MAX_BODY_PX = 1000         # two lines of the 555 px body label, CJK 28 px / ASCII ~15 px


def width(text: str) -> int:
    return sum(28 if ord(c) > 0x2E80 or c in "，。：；" else 15 for c in text)


def load():
    glyphs = set((ROOT / "scripts/tab5_dynamic_symbols.txt").read_text(encoding="utf-8"))
    glyphs |= {chr(i) for i in range(0x20, 0x80)}
    rows = {key: [] for key in CATS}
    errors = []
    for number, line in enumerate(TSV.read_text(encoding="utf-8").splitlines(), 1):
        if not line.strip() or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) != 4 or parts[0] not in CATS:
            errors.append(f"line {number}: expected category<TAB>title<TAB>body<TAB>source")
            continue
        category, title, body, source = parts
        missing = sorted({c for c in title + body + source if c not in glyphs})
        if missing:
            errors.append(f"line {number}: glyphs not in the font: {''.join(missing)}")
        if len(title) > MAX_TITLE_CHARS:
            errors.append(f"line {number}: title longer than {MAX_TITLE_CHARS} characters")
        if width(body) > MAX_BODY_PX:
            errors.append(f"line {number}: body too long for two lines ({width(body)} px)")
        rows[category].append((title, body, source))
    return rows, errors


def cstr(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    rows, errors = load()
    for key, items in rows.items():
        if not items:
            errors.append(f"category {key} is empty")
    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1
    lines = ["// Generated by scripts/generate_clinical_pearls.py from scripts/clinical_pearls.tsv. Do not edit."]
    for key, name in CATS.items():
        lines.append(f"static const Tab5Pearl {name}[] = {{")
        for title, body, source in rows[key]:
            lines.append(f"    {{{cstr(title)}, {cstr(body)}, {cstr(source)}}},")
        lines.append("};")
    text = "\n".join(lines) + "\n"
    if "--check" in sys.argv:
        return 0 if OUT.exists() and OUT.read_text(encoding="utf-8") == text else 2
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT} ({sum(len(v) for v in rows.values())} pearls)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
